### ISSUE TITLE
The watermark module is missing

### ISSUE THREAD

**Issue by carmocca** [rasbt/faster-pytorch-blog#3]
```py
Traceback (most recent call last):
  File "/home/carmocca/git/lightning/faster-pytorch-blog/4_compile.py", line 16, in <module>
    from watermark import watermark
ModuleNotFoundError: No module named 'watermark'
```

**Comment by rasbt** [comment]
ah, do a

`pip install watermark`

or `conda install watermark -c conda-forge`

It's from https://github.com/rasbt/watermark

**Comment by carmocca** [comment]
Ah sorry! I thought this was meant to be a local module like https://github.com/rasbt/faster-pytorch-blog/blob/main/local_dataset_utilities.py. Since there's no requirements, it's hard to tell. Closing

**Comment by rasbt** [comment]
Since it was just a blog post, I cut some corners here, but yeah, adding a requirements.txt is probably a good idea. Just added it here

https://github.com/rasbt/faster-pytorch-blog/blob/e14b76db11980e00a417d2316c74ccfcd609e555/requirements.txt#L1-L6
