### ISSUE TITLE
SSLError

### ISSUE THREAD

**Issue by xiongmozhou** [rasbt/faster-pytorch-blog#7]
```
: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /distilbert-base-uncased/resolve/main/tokenizer_config.json (Caused by  SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1125)')))
```

Python 3 Run 1_ Exception reported during Pytorch distilbert. py

The code line number is 105

Tokenizer=Autotokenizer. from_ Pre trained ("distilbert base uncased", verify=False)pretrained("distilbert-base-uncased",verify=False)

**Comment by rasbt** [comment]
Hi there, 
the code seems to work for me, I think this error is related to the Hub having server problems when downloading the pretrained the model. Usually, this is resolves after some time. I would try it again.
